### PR TITLE
Fix sed error on install script when in MacOS

### LINKED ISSUE #1: Install on mac has sed error.
When installing I get an error from `sed`:

```
$ asdf install clojure 1.9.0
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 18.6M  100 18.6M    0     0  6004k      0  0:00:03  0:00:03 --:--:-- 6005k
x clojure-tools/
x clojure-tools/install.sh
x clojure-tools/clj.1
x clojure-tools/example-deps.edn
x clojure-tools/clojure-tools-1.9.0.381.jar
x clojure-tools/clojure
x clojure-tools/clojure.1
x clojure-tools/clj
x clojure-tools/deps.edn
sed: 1: "clojure": command c expects \ followed by text

Clojure 1.9.0 has been installed. Activate globally with:

    asdf global clojure 1.9.0

Activate locally in the current folder with:

    asdf local clojure 1.9.0
```

### PR DESCRIPTION
**Pull request by mracos**
Sed on MacOS needs an argument after the `-i` flag
Also adds the `-e` that specifies the sed command to run

Fixes #1

### CODE REVIEW

**Comment by mracos** [comment]
This is really weird, the build is failing on Linux because of some weird java error and also on MacOS because of the `sed` command, but in `MacOS 10.14 Mojave` with the kernel `18.0.0` it works ok 🤔

**Comment by mracos** [comment]
It actually was not a problem with `sed`, but with the test script in `.travis.yml`.

Since it is hard-coded to you repo it were not testing the changed code in the PR. :sweat_smile:

Removing the quotes from the `clojure -e '(clojure-version)'` command and making the repo dynamic that `asdf` tests in `.travis.yml` fixed it.

Here is the test passing after https://travis-ci.org/mracos/asdf-clojure/builds/444539838

sorry to bother @halcyon :smile:

**Comment by halcyon** [comment]
@mracos thank you for bringing this to my attention. While I own a mac, my daily driver is linux. 

After looking into the problem, it appears that the BSD version of `sed`, which is what MacOS ships with requires a backup file extension be provided for making a backup file when the `-i` edit in place option is used.  This is optional when using the GNU variant popular on linux systems.  The convention I've seen used by sed practioners is `.bak`. I'll create a new PR reflecting this, and will additionally look into incorporating your contribution around `$TRAVIS_REPO_SLUG` to ensure future PRs will run on Travis. Thank you for you help and patience! Also thanks to @squaresurf for reporting the issue.

**Comment by mracos** [comment]
Yep, I saw that, but now we don't create a backup file so I did not want to change the current behavior. 😅

About the `$TRAVIS_REPO_SLUG`, maybe we can think about using the `$TRAVIS_BUILD_DIR` since it will not be locked to the master branch of the repo running the travis build. But I did not test if this is possible.

Thanks for the looking into it, nice plugin! :heart:

**Comment by halcyon** [comment]
I didn't have any luck with `TRAVIS_BUILD_DIR`. `TRAVIS_BRANCH` seems the more likely choice for testing against a branch that isn't `master`, but I think we'd need some support for utilizing the branch-name in asdf's `plugin-test` command.

**Comment by halcyon** [comment]
Addressed in PR #3. Tested on High Sierra. Will test on Mojave after upgrading tonight.

**Comment by mracos** [comment]
That is right, I will open an issue on the [asdf-vm/asdf](https://github.com/asdf-vm/asdf) repo about this.

Just tested your `master` on Mojave, all good here. Thanks! :smile:

**Pull request closed without merging**
