### PR TITLE
adds latest release

### LINKED ISSUE #11: Clojure v1.11.0 was released
https://clojure.org/news/2022/03/22/clojure-1-11-0

🎉

### PR DESCRIPTION
**Pull request by simonneutert**
https://clojure.org/releases/devchangelog

closes #11

### CODE REVIEW

**Comment by meinside** [comment]
Now latest is [1.11.1](https://clojure.org/releases/devchangelog#_release_1_11_1).

**Comment by bigodel** [comment]
i'll try to come up with a way to get the latest release that doesn't depend on manually specifying it, should be sending a PR this week

**Comment by bigodel** [comment]
i found a solution on [another `asdf-clojure` repo](https://github.com/asdf-community/asdf-clojure/blob/master/bin/list-all). i'd suggest using the following to get all versions:

```clojure
#!/usr/bin/env bash

set -euo pipefail

git ls-remote --tags --refs https://github.com/clojure/brew-install.git |
    grep -o 'refs/tags/.*' |
    cut -d/ -f3- |
    grep -E '[0-9].[0-9].[0-9].[0-9]' |
    sort --version-sort
```

this would replace the `list-all` script.

**Comment by halcyon** [comment]
Sorry for the late response! I'll try this!

**Pull request closed without merging**
